config/routes.rb
ProjectList::Application.routes.draw do

  devise_for :users

  root :to => 'projects#index'
  resources :projects
  resources :user_session
  resources :user
  resources :task

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :project_description, :project_name, :project_status
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :task_description, :task_name, :task_priority
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/users.rb
class Users < ActiveRecord::Base
  attr_accessible :password, :role, :user_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :authenticate_user!
  protect_from_forgery

  	private

  	def auth
 	 	@user = Users.find_by_user_name(params[:user_name])
		@pass = Users.find_by_password(params[:password])

		if @user.id == @pass.id
			redirect_to projects_path

		else
			redirect_to new_user_session_path
		end
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index
		@project = Project.new
		@projects = Project.all
	end

	def show
	end

	def edit
		@project = Project.new
		@projects = Project.find(params[:id])
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(params[:project])
		@project.save
		redirect_to projects_path
	end

	def update
		@projects = Project.find(params[:id])
		@projects.update_attributes(params[:project])

		@project = Project.find(params[:id])
		if @project.project_status.nil?
			@project.update_attribute(:project_status, 1)
		elsif @project.project_status == 1
			@project.update_attribute(:project_status, 0)
		elsif @project.project_status == 0
			@project.update_attribute(:project_status, 1)
		end
		redirect_to projects_path
	end

	def destroy
		@project = Project.find(params[:id])
		@project.destroy
		redirect_to projects_path
	end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
	def index
		@task = Task.new
	end

	def show
	end

	def new
	end

	def create
	end

	def edit
	end

	def update
	end

	def destroy
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	layout 'devise_layout'
	def index
		
	end

	def new
	end

	def show
	end

	def create
	end

	def update
	end

	def destroy
	end
end

app/controllers/user_session_controller.rb
class UserSessionController < ApplicationController
	def new
	end

	def show
	end

	def create
	end

	def update
	end

	def destroy
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_session_helper.rb
module UserSessionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectList</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.0/jquery-ui.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="translucent_overlay"></div>
	<div id="wrapper">
		<% if !user_signed_in? %>
			<%= image_tag 'floating_paper.jpg', :id => 'left-img' %>
		<% end %>

		<% if user_signed_in? %>
			<%= render :partial => 'shared/top_nav' %>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/projects/_delete_pannel.html.erb
<div class="delete_pannel_wrapper<%= id %>" id="delete_pannel_wrapper">
	<div id="delete_pannel_header">Confirm deletion<span id="<%= id %>" class="delete_pannel_close_btn">X</span></div>
	<div id="delete_pannel_body">Do you really want to delete this project?</div>
	<div id="delete_pannel_actions">
		<%= link_to "Delete", project_path(id), :method=>:delete, :class=>:destroy %>
	</div>
</div>

app/views/projects/_form.html.erb
<div id="new_project_form_wrapper">
	<div id="arrow"></div>
	<%= form_for(@project) do |f| %>
		<%= f.label :project_name %>
		<br />
		<%= f.text_field :project_name, :id => 'project_name_txt' %>
	
		<br />
		<br />
		<%= f.label :project_description %>
		<br />
		<%= f.text_area :project_description, :size => '28x8', :id => 'project_desc_txt', :maxlength => "300" %>
		<br />
		<span>*300 characters max</span>
		<span id="char_right"><span>You have </span><strong><span id="char_left">300</span></strong><span> characters left</span></span>

		<br />
		<br />

		<%= f.submit :id => 'save_project_btn' %>
	<% end %>
</div>

app/views/projects/edit.html.erb
<div>
	<div id="new_project_wrapper">
		<%= render :partial => 'projects/form' %>
	</div>
	<div id="all_proj_list">
	<h3>Edit</h3>
	<%= form_for @projects do |f| %>
		<%= f.label :project_name %>
		<br />
		<%= f.text_field :project_name %>

		<br />
		<br />

		<%= f.label :project_description %>
		<br />
		<%= f.text_field :project_description %>
		
		<br />
		<br />

		<%= f.label 'Check if complete' %>
		<%= f.check_box :project_status %>

		<br />

		<%= f.submit 'Save' %>
	<% end %>
	<%= link_to 'Cancel', projects_path %>
	
</div>
</div>

app/views/projects/index.html.erb
<div>
	<div id="new_project_wrapper">
		<%= render :partial => 'projects/form' %>
	</div>

	<div id="all_proj_list">
		<div id="filter_wrapper">

		</div>

		<table class="home_projects_table">
			<h3 id="top_info">Listing all Projects</h3>
			<tr class="header-row">
				<th>Project Name</th>
				<th>Short Description</th>
				<th>Created On</th>
				<th>Status</th>
				<th></th>
				<th>Actions</th>
				<th></th>
				<th></th>
			</tr>
		
			<% @projects.each do |project| %>
				<tr class="<%= cycle('even', 'odd') %>" id="proj_row<%= project.id %>">
					<td class="project_name"><%= project.project_name %></td>
					<td class="project_descript">
						<span class="project_desc_short" id="des_shortproj_row<%= project.id %>"><%= truncate(project.project_description, :length => 40) %></span>
						<span class="project_desc_long" id="des_longproj_row<%= project.id %>"><%= project.project_description %></span>
					</td>
					<td>
						<%= project.created_at %>
					</td>
					<% if project.project_status.nil? %>
						<td class="status_cell">
							<%= link_to 'Not Complete', project_path(project.id, project.project_status), :method => :put, :id => 'proj_status_btn' %>
						</td>
					<% elsif project.project_status == 1 %>
						<td id="status_complete" class="status_cell">
							<%= link_to 'Complete', project_path(project.id, project.project_status), :method => :put, :id => 'proj_status_btn' %>
						</td>
					<% else %>
						<td class="status_cell">
							<%= link_to 'Not Complete', project_path(project.id, project.project_status), :method => :put, :id => 'proj_status_btn' %>
						</td>
					<% end %>
					<td></td>
					<td>
						<span class="delete_btn" id="<%= project.id %>">Delete</span>
					</td>
					<%= render :partial => 'delete_pannel', :locals => {:id => project.id} %>
					<td>
						<%= link_to 'Edit', edit_project_path(project.id) %>
					</td>
					<td>
						<%= link_to 'Task setup', task_index_path, :id => 'task-setup' %>
					</td>
				</tr>
			<% end %>
		</table>
	</div>
</div>

app/views/projects/new.html.erb
<div id="new_project_form_wrapper">
	<h3>Create new project</h3>
	<%= form_for(@project) do |f| %>
		<%= f.label :project_name %>
		<br />
		<%= f.text_field :project_name, :id => 'project_name_txt' %>
	
		<br />
		<br />
		<%= f.label :project_description %>
		<br />
		<%= f.text_area :project_description, :size => '28x8', :id => 'project_desc_txt', :maxlength => "300" %>
		<br />
		<span>*300 characters max</span>
		<span id="char_right"><span>You have </span><strong><span id="char_left">300</span></strong><span> characters left</span></span>

		<br />
		<br />

		<%= f.submit %>
	<% end %>
</div>

app/views/shared/_top_nav.html.erb
<div id="top_nav">
	<%= link_to 'Add new project', new_project_path, :id => 'add_project_btn' %>
	<%= link_to 'Log out', destroy_user_session_path, :id => 'log_out_btn', :method => :delete %>
	<h1 id="application_title">Projects V 1.0</h1>
</div>

app/views/task/index.html.erb
<div id="task-setup-wrapper">
	<% form_for @task, :url => task_index_path do |f| %>
		<div>
			<%= f.label :task_name %>
			<br />
			<%= f.text_field :task_name %>
		<div>
	<% end %>
</div>

app/views/user_session/new.html.erb
<%= form_tag user_session_index_path do %>
	<%= label_tag :user_name %>
	<br />
	<%= text_field_tag :user_name, params[:user_name] %>

	<br />
	<br />

	<%= label_tag :password %>
	<br />
	<%= password_field_tag :password %>
	<br />
	<br />

	<%= submit_tag %>
<% end %>